### PR TITLE
Use transform class to extract away Proc/Klass logic

### PR DESCRIPTION
**Pull request by ollie**
Hi,

I'm sorry but I couldn't resist it. I wrapped your transforms into another class so that it exposes the same interface for class or proc, which has the benefit of removing the if/else logic from control and runner files. I also extracted away the transform application into a separate method so that it looks a bit cleaner.

Feel free to use or discard this entirely, I was just curious if I could improve it and if so would like to share the result. :-)

Ollie

### CODE REVIEW

**Comment by thbar** [comment]
No problem! Thanks for sharing :smile: 

I have been thinking about this, but wanted to take the time to think about how to abstract without having an extra indirection cost for the block form. As well, I'm considering writing a "runner" that will actually unroll the code completely, using some method generation.

Thanks for your code, this gives me food for thought nonetheless! I will digest all this and do some benchmarks (with large processing) to make an informed decision here.

**Comment by ollie** [comment]
Hello, should I close this? Or not yet? :-)

**Comment by thbar** [comment]
No, please keep this opened (unless this bugs you, I can recreate separate issues)! This acts as a reminder for me to apply the whitespaces fixes to the whole codebase, and to think about the wrapper aspect. Thanks!

**Comment by ollie** [comment]
Okey, no problem. :)

**Comment by ollie** [comment]
I don't know if you know Rubocop or not, so please forgive me if you do, but if you don't, I strongly recommend it, it's a great helper (but do not follow it blindly). Here are two rake tasks that I often use to check things in one go: https://github.com/ollie/after_ship/blob/master/Rakefile#L3-L13, feel free to steal 'em if you are so inclined. :-)

**Comment by thbar** [comment]
I know about Rubocop but haven't started using it here! (I'm using CodeClimate though). I will most likely start using it soon though. Thanks for your rake tasks, I'll use them as inspiration!

**Comment by thbar** [comment]
Closing, a similar refactoring is ongoing in #14. Thanks!

**Comment by ollie** [comment]
No problem man! :smile:

**Pull request closed without merging**
