### PR TITLE
Readme tweak

### PR DESCRIPTION
**Pull request by ollie**
Hello,

it is not necessary to use file extension in require and it feels non-idiomatic. Therefore I thought I'd make a PR, if that's okay for such a small change. :-)

Ollie

### CODE REVIEW

**Comment by thbar** [comment]
Hi Ollie! Thanks for pointing that out! Non idiomatic indeed.

I checked my ETL script for an upcoming article and it actually seems that you'd even need something else: either `require './common'` or `require_relative 'common'`, for this to work for real, as `require 'common'` will raise `cannot load such file` unless you tweak the `$LOAD_PATH`.

I'd go for `require_relative` here since it feels better. What do you think?

**Comment by ollie** [comment]
Yes indeed, `require_relative` sounds even better. :smile:

**Comment by thbar** [comment]
You change has been merged into master (b6e02414448c8a9eaa0fd91aa60ffc2c4d4c8b74). Thanks Ollie!

**Comment by ollie** [comment]
No problem, thanks too. :)

**Pull request closed without merging**
